<?php
/** Product copy based on the original catalogue, not manufactured claims. */
return [
4432=>['Black Leather-Look Cut-Out Bodysuit','Black bodysuit with a high-waisted cut, glossy leather-look panels, front and back cut-outs, and a zip neckline.','A graphic black option for close-up creator photography and high-contrast studio looks.'],
4420=>['Blue Floral Embroidered Bra & Thong Set','Two-piece sheer lingerie set with blue floral embroidery, an underwired bra and a matching thong.','The blue detail adds contrast to neutral backdrops in creator portraits and webcam styling.'],
4402=>['Purple Embroidered Four-Piece Lingerie Set','Purple lingerie look with an embroidered sheer top, thong, stockings and matching gloves.','A coordinated outfit with several visible details for full-length shoots and livestream looks.'],
4221=>['Floral Embroidered Underwire Bra & Thong Set','Sheer underwire bra and matching thong with multicolour floral embroidery. Select from the listed colour and size combinations.','Floral detailing gives close-up images a distinct focal point; check the colour swatch before ordering.'],
4181=>['Floral Bra & Thong Set with Sheer Panels','Matching bra and thong combining opaque panels, transparent sections and a floral print.','A two-piece option for contrast-led photography or an understated creator wardrobe.'],
3997=>['Floral Lace Longline Bra & Thong Set','Longline underwired lace bra with a matching thong and floral detailing. Available in the colours shown on this product page.','A defined lace silhouette for portrait shoots; the thong size corresponds to the selected bra size.'],
3487=>['Sheer Long-Sleeve Top & Thong Set','Transparent two-piece set with a close-fitting long-sleeved top and matching thong.','Long sleeves and sheer panels create a different outline from a conventional bra-and-thong set.'],
3475=>['Black Bodysuit with Chain & Garter Detail','Black bodysuit combining sheer and opaque sections with chain-style accents and attached garter-inspired straps.','Contrast panels and strap detailing make this piece suitable for graphic studio styling.'],
3445=>['Floral Three-Piece Lingerie & Garter Set','Three-piece set with a bra, matching bottoms and garter belt, finished with floral embroidery and sheer sections.','A coordinated look for creators who want the garter belt visible in full-length frames.'],
3423=>['Gold-Ring Strappy Lingerie Set','Three-piece set featuring a bra, panties and garter belt with thigh straps, wide bands and gold-tone ring details.','The ring hardware and wide straps provide definition in closely framed images.'],
3381=>['Lace Bodysuit with Wide Straps & Ruffles','Lace bodysuit with wider shoulder straps and ruffled thigh-strap detailing.','Use it as a single-piece outfit when you want a lace silhouette without assembling a set.'],
3355=>['Five-Piece Lingerie Set with Double Skirts','Five-piece look comprising a bra, thong, collar, sheer skirt and a second skirt with thigh straps. Gloves shown in photographs are not included.','Layer the skirts for different compositions within one creator shoot.'],
3304=>['Bright Sheer Four-Piece Garter Set','Coordinated sheer set with bra, thong, garter belt and thigh bands in bright colour options.','The contrasting bands and colours are focal details against plain studio backgrounds.'],
3269=>['Collar & Thigh-Strap Lingerie Set','Strappy lingerie set with a collar-style bra, matching thong and adjustable thigh straps.','A structured, strap-led silhouette for creator photography and webcam outfits.'],
3250=>['Tassel Halter Lingerie & Thigh-Strap Set','Set with a tassel-detail halter bra, matching panties, necklace and thigh straps, plus a keyhole back.','The tassel and necklace details give close-up shots a distinctive finish.'],
3222=>['Sheer Brazilian-Cut Briefs','Brazilian-cut briefs with semi-transparent panels and a streamlined silhouette.','A minimal bottom option for styling with existing lingerie pieces.'],
3191=>['Lace Thong with Heart & Strappy Back','Lace and sheer thong featuring a strappy back and a small heart-shaped metal accent.','The back detail is worth showing in close-up product and creator photography.'],
3180=>['Sheer & Opaque Bra and Panty Set','Matching bra and panties with a mix of sheer and opaque sections and gold-tone ring hardware.','A coordinated two-piece set for contrasting texture and hardware in portraits.'],
3109=>['Sheer-Front Lace-Back Thong with Bow','Low-rise thong with a sheer front panel, lace back and bow detail.','Pair this style with a separate bra for a mixed-texture lingerie look.'],
3097=>['Lace-Up Corset Three-Piece Set','Three-piece lingerie set with a lace-up corset, matching lace thong and fishnet stockings.','The lacing and stockings create a coordinated look for full-length photography.'],
3057=>['Sheer Lace Bra & Panty Set','Two-piece lingerie set featuring a sheer lace bra and matching panties.','A matching lace look that can be styled for portraits or intimate apparel photography.'],
3043=>['Wide Lace Bra with Fine Straps','Wide lace bra with a lace overlay and thin adjustable straps.','Wear it as a separate or build a lace-focused look around it.'],
3021=>['Sheer Bodysuit with Blue Straps','Transparent bodysuit with bold blue straps and a contrasting silhouette.','The blue lines stand out clearly in high-contrast studio portraits.'],
2966=>['Strappy Three-Piece Bra & Garter Set','Three-piece lingerie look featuring a strappy bra, garter belt and matching thong.','A set for creators who want the strap pattern visible in the frame.'],
2955=>['Sheer Lace Three-Piece Garter Set','Matching sheer lace bra, thong and garter belt with coordinated strap details.','A lace-led three-piece look for full-length creator shoots.'],
2934=>['Off-Shoulder Strapless Corset','Strapless corset with off-shoulder styling and a structured corset silhouette.','An open neckline that can work as a focal point in close-up portraits.'],
2908=>['Floral Embroidered Thong','Thong with floral embroidery across the back.','A small-detail piece to combine with an existing lingerie look.'],
2893=>['Emerald Floral Four-Piece Garter Set','Emerald-coloured ensemble with a bra, thong, garter belt and coordinating suspenders, finished with sheer floral detailing.','The emerald tone adds colour to a neutral studio setup.'],
2890=>['Black Sheer Cut-Out Ring Bodysuit','Black sheer bodysuit with adjustable straps, a circular neckline cut-out and a metallic ring detail.','A single-piece look with a distinct geometric centre detail.'],
2838=>['Silver-Strap Three-Piece Garter Set','Matching bra, garter belt and thong featuring shiny silver-coloured straps.','Reflective strap detailing can be picked up in close-up imagery and creator shoots.'],
];
